language: go

go:
    - "1.12"
    - master

matrix:
    allow_failures:
        - go: master

before_install:
    # https://github.com/golang/dep
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
    - make travis -j 8

notifications:
    email: false
    webhooks:
        urls:
            - https://lism.in/travis
        on_success: always
        on_failure: always
        on_start: always
