## The root configuration file for [popuko](https://github.com/karen-irc/popuko)

# The version of this configuration format.
config_version = 0

# This bot name.
botname = "popuko"

# The port number which this application listening.
port = 3000

[github]
# If your github bot name is different from global botname,
# please specify this. Otherwise, you should set empty string.
botname = ""

# GitHub API Token
api_token = "api_token"

# GitHub Webhook secret
webhook_secret = "webhook_secret"

# For security reasons, you can restrict a repository which this bot supports.
#   - If this list is empty, this bot accepts all webhook incoming from any repositories.
#   - Otherwise, this bot only accepts the webhook from repositories listed in this item.
accepted_repositoies = [ "karen-irc/popuko" ]
