
[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "1c3f0aaee1ce742b655f1ba8f33740103e904c5c"
